### ISSUE TITLE
Transpose Conv conversion

### ISSUE THREAD

**Issue by Ziva1011** [M3DV/ACSConv#22]
Hi, I'm using your library to convert segmentation models from 2D to 3D. In segmentation, transpose convolution layers are common and your library does not seem to include this conversion. We forked your repo and implemented some changes to include these types of layers [in the following repo](https://github.com/a1302z/ACSConv). However this code does not work. I have tried to debug it and the problem seems to be in the [file functional.py on the acs_conv_f function](https://github.com/a1302z/ACSConv/blob/master/acsconv/operators/functional.py), where we split the kernel in 3  (a,c,s) and then we concatenate the 3 3D conv layers together. When the same is done for transposed convolutions, the sizes of the produced layers do not match and throws an error because it can not concatenate arrays with different dimensions.

Would you be able to maybe share a light on what we are implementing wrong?

Thank you in advance!

**Comment by Ziva1011** [comment]
So I have a minimal reproducible example

```
import torch

from acsconv.converters import ACSConverter

model = torch.nn.Sequential(torch.nn.ConvTranspose2d(1, 64, kernel_size=4, stride=(2, 2, 2), padding=(1, 1, 1)))
model_3d = ACSConverter(model)

data = torch.randn(1, 1, 128, 128, 64)
out = model_3d(data)
```

And the error occurs when I run the last line

```
Exception has occurred: RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Sizes of tensors must match except in dimension 1. Expected size 255 but got size 256 for tensor number 1 in the list.
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/site-packages/acsconv/operators/functional.py", line 150, in acs_conv_f
    f = torch.cat(f_out, dim=1)
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/site-packages/acsconv/operators/acsconv.py", line 151, in forward
    return acs_conv_f(
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/site-packages/acsconv/converters/base_converter.py", line 120, in __call__
    return self.model(x)
  File "/home/piresc/dp-thesis/acs_converter_test.py", line 25, in <module>
    out = model_3d(data)
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/piresc/miniconda3/envs/torchsegmentation/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 255 but got size 256 for tensor number 1 in the list.
```

**Comment by Ziva1011** [comment]
```
a.shape
torch.Size([1, 22, 255, 256, 128])
c.shape
torch.Size([1, 21, 256, 255, 128])
s.shape
torch.Size([1, 21, 256, 256, 127])
```

The weights for the these tensors have the following sizes:

```
weight_a.shape
torch.Size([1, 22, 1, 4, 4])
weight_c.shape
torch.Size([1, 21, 4, 1, 4])
weight_s.shape
torch.Size([1, 21, 4, 4, 1])
```

**Comment by seanywang0408** [comment]
The reason of the error is that the input/output size relation of transpose convolution is different from convolution.
First, to calculate the correct output tensor size, we should use the following function to replace conv3D_output_shape_f:
```
def transposeconv3D_output_shape_f(i, input_shape, kernel_size, dilation, padding, stride):
    return (input_shape[i] - 1) * stride[i] + kernel_size[i] - 2 * padding[i]
```
Second, the if-else in L83-L93 in [functional.py](https://github.com/a1302z/ACSConv/blob/master/acsconv/operators/functional.py) is to conduce additional padding to output correct shape for the unsqueeze dimension. But it's only for convolution, while for transpose convolution the if-else would be different, since padding in transpose convolution have different meaning. I haven't think it through yet at the moment. But I think it could be fixed with some modification. The overall target is to produce the right size on the unsqueeze dimension.

This is also one of the reason that we did not implement transpose convolution back then. We thought that it might involve over-complicated code. Besides, in many cases, transpose convolution could be replaced by upsampling.
